version: '3.7'

x-op-keys: &keys
  environment:
    KEYMASTER_USERNAME: ${ANONYMOUS_USER:-my_syncope}
    KEYMASTER_PASSWORD: ${ANONYMOUS_KEY:-my_syncope}
    ANONYMOUS_USER: ${ANONYMOUS_USER:-my_syncope}
    ANONYMOUS_KEY: ${ANONYMOUS_KEY:-my_syncope}


services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: syncope
      POSTGRES_USER: syncope
      POSTGRES_PASSWORD: syncope
    volumes:
      - ./db:/var/lib/postgresql/data
  syncope:
    depends_on:
      - db
    image: apache/syncope:3.0.5
#    volumes:
#      - ./syncope:/opt/syncope
    ports:
      - "18080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker,postgresql
      DB_URL: jdbc:postgresql://db:5432/syncope?stringtype=unspecified
      DB_USER: syncope
      DB_PASSWORD: syncope
      DB_POOL_MAX: 20
      DB_POOL_MIN: 5
      OPENJPA_REMOTE_COMMIT: sjvm
      KEYMASTER_ADDRESS: http://localhost:8080/syncope/rest/keymaster
      KEYMASTER_USERNAME: ${ANONYMOUS_USER:-my_syncope}
      KEYMASTER_PASSWORD: ${ANONYMOUS_KEY:-my_syncope}
      SERVICE_DISCOVERY_ADDRESS: http://syncope:8080/syncope/rest/
      ANONYMOUS_USER: ${ANONYMOUS_USER:-my_syncope}
      ANONYMOUS_KEY: ${ANONYMOUS_KEY:-my_syncope}

  syncope-console:
    depends_on:
      - syncope
    image: apache/syncope-console:3.0.5
#    volumes:
#      - ./syncope-console:/opt/syncope
    ports:
      - "28080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYMASTER_ADDRESS: http://syncope:8080/syncope/rest/keymaster
      KEYMASTER_USERNAME: ${ANONYMOUS_USER:-my_syncope}
      KEYMASTER_PASSWORD: ${ANONYMOUS_KEY:-my_syncope}
      SERVICE_DISCOVERY_ADDRESS: http://syncope-console:8080/syncope-console/
      ANONYMOUS_USER: ${ANONYMOUS_USER:-my_syncope}
      ANONYMOUS_KEY: ${ANONYMOUS_KEY:-my_syncope}

  syncope-enduser:
    depends_on:
      - syncope
    image: apache/syncope-enduser:3.0.5
#    volumes:
#      - ./syncope-enduser:/opt/syncope
    ports:
      - "38080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYMASTER_ADDRESS: http://syncope:8080/syncope/rest/keymaster
      KEYMASTER_USERNAME: ${ANONYMOUS_USER:-my_syncope}
      KEYMASTER_PASSWORD: ${ANONYMOUS_KEY:-my_syncope}
      SERVICE_DISCOVERY_ADDRESS: http://syncope-enduser:8080/syncope-enduser/
      ANONYMOUS_USER: ${ANONYMOUS_USER:-my_syncope}
      ANONYMOUS_KEY: ${ANONYMOUS_KEY:-my_syncope}
